### PR TITLE
Change name by number in Sprint

### LINKED ISSUE #75: Change Sprint name by Sprint number
It should be an integer and not an string anymore. It should be always present.

TASK FOR THE FUTURE:

- In the future we could try to generate one by default, by currently it is enough if it is introduced manually.

- The number of the Sprint should't be changed if the Sprint was already started.

### PR DESCRIPTION
**Pull request by DavidKang**
We remove the attribute name and added number because trollolo needs a
number.

should resolve #75

### CODE REVIEW

**Comment by Ana06** [comment]
@DavidKang can you please deploy this? :wink:

**Comment by Ana06** [comment]
@DavidKang 

> Apart from that LGTM. Thanks @DavidKang

Ouch! I reviewed this with the bot hahha

**Comment by DavidKang** [comment]
> @DavidKang can you please deploy this? 😉

Done 😸

**Comment by Ana06** [comment]
[(3) P19: Frontpage: Burndown Chart](https://trello.com/c/Gm0FGST1/567-3-p19-frontpage-burndown-chart)

**Pull request merged**
