### PR TITLE
Fix name on team page

### PR DESCRIPTION
**Pull request by bgeuken**

### CODE REVIEW

**Comment by DavidKang** [comment]
@bgeuken, please fix the commit message :smile_cat:

**Comment by bgeuken** [comment]
You can get this information from the commit diff. It's not like this is a massive change or needs detailed explanation.

**Comment by Ana06** [comment]
@bgeuken 

> You can get this information from the commit diff. It's not like this is a massive change or needs detailed explanation.

you can get everything from the commit diff. But it is always nice to make this easier. Anyway this is the current git-cop configuration, we can discuss about changing it (although I would personally prefer not to do so), but nobody complained when this was added.

**Comment by bgeuken** [comment]
I think you are missing the point of commit messages and emphasize to much on a general rule (explaining in a commit message why a change was made). The rule is fine, but it seems pointless to request this for typo fixes and alike.

Though, if this is required by git-cop, I can add some text there to make git-cop happy.

**Comment by mdeniz** [comment]
Then do it! hahaha
I also don't see the point in fixing of a typo, is too much overhead, but anyway.

**Comment by mdeniz** [comment]
I meant... stop talking. 

The git-cop config that we have is like it is and we agreed on that. If you want we talk and maybe change the thing... but spending 3 comments in defending your opinion instead of adding a dummy message and after discuss if the rule still makes sense... I don't really get the point.

Either add the commit message as we have this in our github workflow or don't follow the rules and force the merge. Too much time wasted I think.

Is it more clear now? 😄

**Comment by mdeniz** [comment]
And BTW your name was copied from https://wiki.microfocus.net/index.php?title=SUSE-Development/OPS/BuildSolutions and it still misspelled there

**Comment by Ana06** [comment]
@bgeuken @mdeniz the main idea of adding git-cop is avoiding this kind of discussions about things that are not that important but that make us wasting a lot of time. I would suggest to always make git-cop happy and if someone doesn't agree on git-cop configuration we discuss this somewhere else. It is true that when I added the git-cop configuration file, I didn't copied exactly what we have in OBS as there is less people here and I thought we could try some more things (also we are not using tags here).

So, @bgeuken could you mind making git-cop happy and then openning an issue/PR to discuss the git-cop rules you are not happy with. If this cop rule really annoy you, I am fine with removing it. I would personally prefer to keep it, but the idea of having git-cop is just to now what is the agreement of the team with which everybody is comfortable.

**Pull request merged**
