### PR TITLE
Removed label overflow in Dashboard

### LINKED ISSUE #107: Git PR section label overflow
labels get overflow from the parent div, and aren't scrollable . So,some of them aren't visible.
Instead of showing them in a row, select tag or x-overflow:auto can be used for the same purpose.

### PR DESCRIPTION
**Pull request by namangupta01**
Closes #107

### CODE REVIEW

**Comment by namangupta01** [comment]
Here's how it looks now ->

screen shot 2018-01-19 at 3 47 18 am

**Comment by DavidKang** [comment]
@namangupta01, Thanks for your contribution! 😸

**Comment by DavidKang** [comment]
@namangupta01, IMO your changes don't solve the issue, because, what happens if you have 10 labels or more?

**Comment by Ana06** [comment]
@namangupta01 what is the state of this?

**Comment by Ana06** [comment]
Closing as @namangupta01 to allow that someone works on this.

**Pull request closed without merging**
